// Universal Visual Testing (UVT) Configuration File
// Auto-generated by: uvt init (URAE v1)
// Framework detected: SvelteKit
// Project type: Hybrid
export default {
  // Visual comparison service provider ("percy" or "playwright")
  provider: 'percy',

  // Framework integration type — "auto" uses Capability Graph Engine
  framework: 'auto',

  // Enable cache for incremental testing
  cache: true,

  // Workers number ("auto" or custom number)
  workers: 'auto',

  // Reports options
  report: {
    html: true,
    json: true
  },

  // Mask dynamic elements (dates, uuids, times, canvases)
  dynamicDetection: true
};
